# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - Master
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: 'production'
      version: '1.0.0'
